const { contextBridge, ipcRenderer } = require('electron')

// Minimal, safe bridge exposed to the renderer as window.pet
contextBridge.exposeInMainWorld('pet', {
  setIgnoreMouse: (ignore, opts) => ipcRenderer.send('pet:set-ignore-mouse', ignore, opts),
  move: (dx, dy, visibleBounds) => ipcRenderer.send('pet:move', dx, dy, visibleBounds),
  setWindowSize: (size) => ipcRenderer.send('pet:set-window-size', size),
  onSetScale: (cb) => ipcRenderer.on('pet:set-scale', (_e, scale) => cb(scale)),
  setHidden: (hidden) => ipcRenderer.send('pet:set-hidden', hidden),
  speak: (text) => ipcRenderer.send('pet:speak', text),
  petAction: () => ipcRenderer.send('pet:pet-action'), // 管理窗口触发「摸摸」
  onDoPet: (cb) => ipcRenderer.on('pet:do-pet', () => cb()),
  feedPet: () => ipcRenderer.send('pet:feed-pet'), // 管理窗口触发「投喂」
  onDoFeed: (cb) => ipcRenderer.on('pet:do-feed', () => cb()),
  openTarget: (target) => ipcRenderer.invoke('pet:open-target', target),
  getLastOpenedTarget: () => ipcRenderer.invoke('pet:get-last-opened-target'),
  sessionPreview: (request) => ipcRenderer.invoke('pet:session-preview', request),
  shareSession: (request) => ipcRenderer.invoke('pet:share-session', request),
  bridgeTasks: (request) => ipcRenderer.invoke('pet:bridge-tasks', request),
  shareBridgeTasks: (request) => ipcRenderer.invoke('pet:share-bridge-tasks', request),
  openBridgeTasksWindow: () => ipcRenderer.invoke('pet:open-bridge-tasks-window'),
  larkInbox: () => ipcRenderer.invoke('pet:lark-inbox'),
  refreshLarkInbox: () => ipcRenderer.invoke('pet:lark-inbox-refresh'),
  onLarkInboxUpdate: (cb) => ipcRenderer.on('pet:lark-inbox-updated', (_e, snapshot) => cb(snapshot)),
  openLarkWorkbench: () => ipcRenderer.invoke('pet:open-lark-workbench'),
  larkAssistantState: () => ipcRenderer.invoke('pet:lark-assistant-state'),
  analyzeLarkMessage: (request) => ipcRenderer.invoke('pet:lark-assistant-analyze', request),
  onLarkAssistantUpdate: (cb) => ipcRenderer.on('pet:lark-assistant-updated', (_e, state) => cb(state)),
  workItemsState: () => ipcRenderer.invoke('pet:work-items-state'),
  createWorkItemFromAssistant: (request) => ipcRenderer.invoke('pet:work-item-create-from-assistant', request),
  createLarkTaskFromWorkItem: (request) => ipcRenderer.invoke('pet:work-item-create-lark', request),
  syncWorkItems: (request = {}) => ipcRenderer.invoke('pet:work-items-sync', request),
  completeWorkItem: (request) => ipcRenderer.invoke('pet:work-item-complete', request),
  setWorkItemPriority: (request) => ipcRenderer.invoke('pet:work-item-priority', request),
  runWorkItemAgent: (request) => ipcRenderer.invoke('pet:work-item-agent', request),
  onWorkItemsUpdate: (cb) => ipcRenderer.on('pet:work-items-updated', (_e, state) => cb(state)),
  knowledgeState: () => ipcRenderer.invoke('pet:knowledge-state'),
  searchKnowledge: (request) => ipcRenderer.invoke('pet:knowledge-search', request),
  saveKnowledgeResult: (request) => ipcRenderer.invoke('pet:knowledge-save-result', request),
  captureKnowledgeIdea: (request) => ipcRenderer.invoke('pet:knowledge-capture-idea', request),
  captureKnowledgeClipboard: () => ipcRenderer.invoke('pet:knowledge-capture-clipboard'),
  summarizeKnowledgeItem: (request) => ipcRenderer.invoke('pet:knowledge-summarize', request),
  onKnowledgeUpdate: (cb) => ipcRenderer.on('pet:knowledge-updated', (_e, state) => cb(state)),
  applyLarkDraft: (request) => ipcRenderer.invoke('pet:lark-draft-apply', request),
  larkBaseSink: () => ipcRenderer.invoke('pet:lark-base-sink'),
  openLarkBase: () => ipcRenderer.invoke('pet:lark-base-open'),
  larkWebPushStatus: () => ipcRenderer.invoke('pet:lark-web-push-status'),
  openLarkWebPush: () => ipcRenderer.invoke('pet:lark-web-push-open'),
  reloadLarkWebPush: () => ipcRenderer.invoke('pet:lark-web-push-reload'),
  onLarkWebPushUpdate: (cb) => ipcRenderer.on('pet:lark-web-push-updated', (_e, status) => cb(status)),
  copyText: (text) => ipcRenderer.invoke('pet:copy-text', text),
  readText: () => ipcRenderer.invoke('pet:read-text'),
  // local Claude Code / Codex hook events forwarded from the main process
  onAgentEvent: (cb) => ipcRenderer.on('agent-event', (_e, event) => cb(event)),
  // growth state (P4)
  getState: () => ipcRenderer.invoke('pet:get-state'),
  saveState: (state) => ipcRenderer.send('pet:save-state', state),
  customStyles: () => ipcRenderer.invoke('pet:custom-styles'),
  importCustomStyle: () => ipcRenderer.invoke('pet:custom-style-import'),
  activateCustomStyle: (id) => ipcRenderer.invoke('pet:custom-style-activate', id),
  deleteCustomStyle: (id) => ipcRenderer.invoke('pet:custom-style-delete', id),
  // token usage stats (P4) — local + Feishu(lark) merged
  tokenStats: () => ipcRenderer.invoke('pet:token-stats'),
  addLarkTokens: (tokens) => ipcRenderer.send('pet:add-lark-tokens', tokens),
  // pomodoro / reminder bubbles from main (P4)
  onNotify: (cb) => ipcRenderer.on('pet-notify', (_e, payload) => cb(payload)),
  getPomodoroSettings: () => ipcRenderer.invoke('pet:pomodoro-settings'),
  updatePomodoroSettings: (settings) => ipcRenderer.send('pet:pomodoro-settings', settings),
  onTogglePanel: (cb) => ipcRenderer.on('pet:toggle-panel', () => cb()),
  onEnterMoveMode: (cb) => ipcRenderer.on('pet:enter-move-mode', () => cb()),
  updateUiMenuState: (state) => ipcRenderer.send('pet:ui-menu-state', state),
  onSetDndMode: (cb) => ipcRenderer.on('pet:set-dnd-mode', (_e, enabled) => cb(enabled)),
  getUpdateStatus: () => ipcRenderer.invoke('pet:update-status'),
  checkForUpdates: () => ipcRenderer.invoke('pet:check-for-updates'),
  installUpdate: () => ipcRenderer.invoke('pet:install-update'),
  onUpdateStatus: (cb) => ipcRenderer.on('pet:update-status-changed', (_e, status) => cb(status)),
  // accessory tray menu state and commands
  updateAccessoryMenu: (state) => ipcRenderer.send('pet:accessory-menu', state),
  onEquipAccessory: (cb) => ipcRenderer.on('pet:equip-accessory', (_e, payload) => cb(payload)),
  onUnlockAccessory: (cb) => ipcRenderer.on('pet:unlock-accessory', (_e, payload) => cb(payload)),
  // accessory shop (management window): read cached catalog + send equip/unlock commands
  getAccessoryCatalog: () => ipcRenderer.invoke('pet:get-accessory-catalog'),
  equipAccessoryCmd: (payload) => ipcRenderer.send('pet:equip-accessory-cmd', payload),
  unlockAccessoryCmd: (payload) => ipcRenderer.send('pet:unlock-accessory-cmd', payload),
  // evolution stages (management window 进化图鉴): pet reports → main cache → manage reads
  reportEvolution: (state) => ipcRenderer.send('pet:evolution-state', state),
  getEvolution: () => ipcRenderer.invoke('pet:get-evolution'),
  // management window <-> pet renderer ui-settings sync (via main cache)
  reportUiSettings: (settings) => ipcRenderer.send('pet:report-ui-settings', settings),
  onApplyUiPatch: (cb) => ipcRenderer.on('pet:apply-ui-patch', (_e, patch) => cb(patch)),
  getUiSettings: () => ipcRenderer.invoke('pet:get-ui-settings'),
  patchUiSettings: (patch) => ipcRenderer.send('pet:patch-ui-settings', patch),
  openManageWindow: () => ipcRenderer.invoke('pet:open-manage-window'),
  // per-display work areas + overlay origin (multi-monitor bubble placement)
  displayAreas: () => ipcRenderer.invoke('pet:get-display-areas'),
  onDisplayAreasChanged: (cb) => ipcRenderer.on('pet:display-areas-changed', (_e, snapshot) => cb(snapshot)),
})
